# Generated by Django 2.1.15 on 2020-08-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cate',
            name='prod',
        ),
    ]
