# Generated by Django 3.0.8 on 2020-07-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prod_id',
            new_name='idd',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='prod_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='message',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
    ]
